### ISSUE TITLE
How to use Drop Down widget with FIR Designer?

### ISSUE THREAD

**Issue by pavel-demin** [pothosware/pothos-comms#16]
I'm not sure if it's a question or an enhancement.

In GNU Radio Companion, I can use a chooser widget to define the lower and upper frequencies of a FIR filter.

A chooser widget with id set to 'mode' has the following options:
- LSB -> [-3000, -300]
- USB -> [300, 3000]

Then I can use these options to define the lower and upper frequencies of a FIR filter by setting taps to
`firdes.complex_band_pass(1, samp_rate, mode[0], mode[1], 100, firdes.WIN_HAMMING)`.

An example flow graph can be found at [this link](https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver/gnuradio/trx_ssb.grc)

Would it be possible to build something similar with Pothos?

**Comment by guruofquality** [comment]
Rather than a taps function (which theoretically could be added) there is a FIR designer block which emits taps and can be controlled with various widgets through the various slots. Example in this screen shot: https://github.com/pothosware/pothos-demos/wiki/Simple-FM-Demod#demodulation-chain

**Comment by pavel-demin** [comment]
It's more or less what I'm trying to do. My problem is that I'd like to control two values (lower and upper frequencies) from one widget (Drop Down) and I don't see how to do it.

In GNU Radio Companion, it's possible with lists and indexes (mode[0], mode[1], etc.). In Pothos, I've tried using Evaluator:
![eval](https://cloud.githubusercontent.com/assets/8037893/12494003/35598516-c088-11e5-8993-85181cacad8b.png)

and I've got the following error message:

```
Pothos.Block.callSlot: Evaluator0[setMode]: Proxy Exception Message: Exception: EvalEnvironment::eval(mode__tmp__0): Undefined token "mode__tmp__0" found at position 0.
```

**Comment by guruofquality** [comment]
I see what you mean. I don't think the evaluator supports array slicing yet. :-(

But this may be just what you need. I added a setFrequencies() call to FIR designer which can support a list of frequencies. So install the master branch of pothos-comms and you should be able to connection the drop down directly to the designer: https://github.com/pothosware/pothos-comms/commit/80e248bfe2121e7d82f86b269badeb5164bcffa2

**Comment by pavel-demin** [comment]
Thanks for this new function. It works great and is indeed what I need.
