### ISSUE TITLE
Add block interleaver

### ISSUE THREAD

**Issue by mhostetter** [pothosware/pothos-comms#23]
I think it would be nice to add a standard block interleaver to Pothos. I'm currently working on that code now. I wanted to discuss how you would like it integrated (if at all!).

As a side note, I would like to add some FEC blocks in the future. So, my first thought was to create a new directory in PothosComms `fec/` and have the `BlockInterleaver` and `BlockDeinterleaver` blocks be the first blocks in there. Interleaving seems to fit best with FEC stuff, but wanted to your feedback before I proceed.

Thanks,
Matt

**Comment by guruofquality** [comment]
Sounds great. Any additions would be appreciated; PothosComms certainly needs some love. So your directory/file organization suggestion sounds good to me -- and by all means, take charge, do as you see fit to sort of best organize/structure things :-)

Theres a small guide to contributing here if that helps:  https://github.com/pothosware/PothosCore/wiki/Contributing But I guess the gist of it is, be mindful of additional dependencies  or code that might complicate the build or licensing. Its easier to just host a new repo than to complicate an existing one.

New dependencies arent really a big deal, I just try to make sure I can do things like make them (or their blocks) optional, submodule in the dependency library to build it when missing, make sure I can build said library into some of the packaging options...etc things like that.
