### ISSUE TITLE
Polymorphic exception is caugh by const value when it should be const reference

### ISSUE THREAD

**Issue by ashley-b** [pothosware/pothos-comms#25]
https://github.com/pothosware/PothosComms/blob/17d9cda18083e098890846427b4643ea1a015c65/filter/FIRDesigner.cpp#L455
Compiler message
warning: catching polymorphic type ‘const class std::runtime_error’ by value [-Wcatch-value=]

**Comment by guruofquality** [comment]
Fixed a while ago, forgot to close: https://github.com/pothosware/PothosComms/commit/f988efcb09a68f3cbe918a09168de01d420c6a67 thx
