### ISSUE TITLE
IIR Filter block documentation lacking

### ISSUE THREAD

**Issue by ashley-b** [pothosware/pothos-comms#26]
I have found the filter taps in /comms/iir_filter block to be in reverse order to what spuce expects.
spuce taps are in b[0], b[..], a[0], a[...] order. 
https://github.com/pothosware/PothosComms/blob/434627b8572fed2fa48f11b7876e196f4da85114/filter/IIRFilter.cpp#L64-L68

Should mention taps are in order of b, a
https://github.com/pothosware/PothosComms/blob/434627b8572fed2fa48f11b7876e196f4da85114/filter/IIRFilter.cpp#L29-L31

Thanks

**Comment by guruofquality** [comment]
I wonder if this could be better with separate feed forward and feedback taps as parameters.

Anyway, I think the library calls into spuce are right. The same guy wrote both spuce and these blocks, so it should be good :-). The taps are organized as {b_taps, a_taps}, and I think this is also true for the spuce library: 

So I think its just an issue with the debug prints being wrong/reversed. Are you seeing the same thing?

From spuce:
```
  void set_taps(const std::vector<Coeff>& taps) {
    // Divide vector in half, 1st half are feedforward, 2nd half feedback
    assert(taps.size() != 0);
    auto size = taps.size()/2;
    zeros.set_size(size);
    poles.set_size(size-1);
    for (size_t i = 0; i < size; i++) { zeros.settap(i, taps[i]); }
    // Skip 1st feedback and negate the rest
    for (size_t i = 0; i < size-1; i++) { poles.settap(i, -taps[i+size+1]); }
}
```

**Comment by guruofquality** [comment]
@audiofilter if there was a way to set the taps as two parameters (feed-forward, feedback) in the iir_df, we could separate out the taps in the designer and block in to separate arrays: https://github.com/audiofilter/spuce/blob/master/spuce/filters/iir_df.h

**Comment by ashley-b** [comment]
I have tested it again with taps from gr_filter_design and the order is B, A. sorry for the false alarm. Its just the debug code thats back to front
Could be handy to have them settable in two separate arrays as they are not always the same length from some generators.
