### ISSUE TITLE
FIR designer remez exchange algorithm

### ISSUE THREAD

**Issue by guruofquality** [pothosware/pothos-comms#7]
Incorporate this into the filter designer
https://github.com/hooleyhoop/HooleyBits/blob/master/FFT%20Explore/remez-19980711/remez.c

**Comment by audiofilter** [comment]
I have C++ code for Remez from spuc library, that I could probably import over/into Pothos. I'll take a look after finishing up IIR stuff

**Comment by guruofquality** [comment]
Cool, sounds good!

**Comment by audiofilter** [comment]
I've pushed support for Remez filters in FIRDesigner. New parameter weight was also added. Please take a look and try out. Let me know if there are issues

**Comment by guruofquality** [comment]
Done. And with your recent rewrite, the FIR designer is even more elegant. Thanks @audiofilter
